# Travis-CI configuration

language: cpp

# :TODO: @brad Add osx build (need homebrew packages)..
matrix:
  include:
    - os: linux
      dist: precise
      env: LD_LIBRARY_PATH="${DEPS_DIR}/lib:${TARGET_DIR}/lib:${LD_LIBRARY_PATH}"
      compiler: gcc
      sudo: false
    - os: linux
      dist: precise
      env: LD_LIBRARY_PATH="${DEPS_DIR}/lib:${TARGET_DIR}/lib:${LD_LIBRARY_PATH}"
      compiler: clang
      sudo: false
    - os: osx
      compiler: clang


# Limit number of commits in cloning (but keep enough so that 'git describe' works)
git:
  depth: 100

# Dependencies installed as packages on Linux
addons:
  apt:
    packages:
      - cmake
      - python-setuptools
      - libcppunit-dev
      - libopenmpi-dev
      - openmpi-common
      - openmpi-bin
      - proj-bin
      - proj-data
      - libproj-dev

# Dependencies installed as packages on OS X
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install proj cppunit mpich pcre; fi

# Build dependencies. Use Proj4 header file to check to see if dependencies are cached.
install:
  - if [ ! -f ${DEPS_DIR}/bin/nemesis ]; then travis/dependencies.sh build; else echo "Using cached dependencies."; fi
  - ls -R ${DEPS_DIR}

script: 
  - autoreconf --install --verbose --force && ./configure --enable-swig --enable-testing --enable-pythia --prefix="${TARGET_DIR}" CPPFLAGS="-I${DEPS_DIR}/include -I${TARGET_DIR}/include" LDFLAGS="-L${DEPS_DIR}/lib -L${TARGET_DIR}/lib" && make -j${MAKE_THREADS} && make install && make -j${MAKE_THREADS} check

env:
  global:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then MAKE_THREADS=2 ; else MAKE_THEADDS=$(nproc); fi
    - PYTHON_VERSION="2.7"
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/dist/deps"
    - TARGET_DIR="${TRAVIS_BUILD_DIR}/dist/target"
    - PATH="${DEPS_DIR}/bin:${TARGET_DIR}/bin:${PATH}"
    - PYTHONPATH="${DEPS_DIR}/lib/python${PYTHON_VERSION}/site-packages:${TARGET_DIR}/lib/python${PYTHON_VERSION}/site-packages:${PYTHONPATH}"

cache:
  timeout: 300
  directories:
    - $DEPS_DIR
